# Generated by Django 5.2.4 on 2025-07-15 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('label', models.CharField(default='Adventure', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('download_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('pc', 'PC')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='game_images/')),
                ('download_link', models.URLField()),
                ('downloads', models.IntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateField()),
                ('youtube_trailer', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameScreenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_screenshots/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='freegamedownload.game')),
            ],
        ),
    ]
