# Generated by Django 5.2.4 on 2025-07-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freegamedownload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='size',
        ),
        migrations.RemoveField(
            model_name='game',
            name='version',
        ),
    ]
